DROP DATABASE IF EXISTS CityLibrary;
CREATE DATABASE CityLibrary;

USE CityLibrary;

/*Create the table*/

CREATE TABLE PUBLISHER(
    PUBLISHERID int NOT NULL auto_increment,
    PUBNAME varchar(250) NOT NULL,
    ADDRESS varchar(250),
    PRIMARY KEY (PUBLISHERID)
  );

CREATE TABLE DOCUMENT (
    DOCID int NOT NULL auto_increment,
    TITLE varchar(250) NOT NULL,
    PDATE date,
    PUBLISHERID int,
    PRIMARY KEY (DOCID),
    FOREIGN KEY (PUBLISHERID) REFERENCES PUBLISHER(PUBLISHERID)
);


CREATE TABLE BOOK (
  DOCID INT NOT NULL,
  ISBN VARCHAR(45) NOT NULL,
  PRIMARY KEY (DOCID),
  FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID)

);


CREATE TABLE AUTHOR (
  AUTHORID INT NOT NULL auto_increment,
  ANAME varchar(45) NOT NULL,
  PRIMARY KEY (AUTHORID)
);


CREATE TABLE WRITES (
  AUTHORID INT NOT NULL,
  DOCID INT NOT NULL,
  FOREIGN KEY (DOCID) REFERENCES BOOK(DOCID),
  FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(AUTHORID)
);



CREATE TABLE PROCEEDINGS (
  DOCID INT NOT NULL,
  CDATE DATE ,
  CLOCATION varchar(45),
  CEDITOR varchar(45),
  PRIMARY KEY (DOCID),
  FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID)
);


CREATE TABLE CHIEF_EDITOR (
  EDITOR_ID INT NOT NULL auto_increment,
  ENAME VARCHAR(45) ,
  PRIMARY KEY (EDITOR_ID)
);


CREATE TABLE JOURNAL_VOLUME (
  DOCID INT NOT NULL,
  JVOLUME VARCHAR(45) ,
  EDITOR_ID INT,
  PRIMARY KEY (DOCID),
  FOREIGN KEY (EDITOR_ID) REFERENCES CHIEF_EDITOR(EDITOR_ID),
  FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID)
);




CREATE TABLE JOURNAL_ISSUE (
  DOCID INT NOT NULL,
  ISSUE_NO INT NOT NULL ,
  SCOPE VARCHAR(255),
  PRIMARY KEY (DOCID, ISSUE_NO),
  FOREIGN KEY (DOCID) REFERENCES JOURNAL_VOLUME(DOCID)
);


CREATE TABLE INV_EDITOR (
  DOCID INT NOT NULL,
  ISSUE_NO INT NOT NULL ,
  IENAME VARCHAR(45),
  PRIMARY KEY (DOCID, ISSUE_NO, IENAME),
  FOREIGN KEY (DOCID,ISSUE_NO) REFERENCES JOURNAL_ISSUE(DOCID,ISSUE_NO)
);


CREATE TABLE BRANCH (
    LIBID int NOT NULL auto_increment,
    LNAME varchar(250),
    LLOCATION varchar(250),
    PRIMARY KEY (LIBID)
    );


CREATE TABLE COPY (
    DOCID int NOT NULL,
    COPYNO int NOT NULL,
    LIBID int NOT NULL,
    COPYPOSITION varchar(250),
    PRIMARY KEY (DOCID,COPYNO,LIBID),
    FOREIGN KEY (DOCID) REFERENCES DOCUMENT(DOCID),
    FOREIGN KEY (LIBID) REFERENCES BRANCH(LIBID)
);


 CREATE TABLE READER (
    READERID int NOT NULL auto_increment,
    RTYPE varchar(250),
    RNAME varchar(250),
    ADDRESS varchar(250),
    PRIMARY KEY (READERID)
    );

   
CREATE TABLE RESERVES (
    RESUMBER int NOT NULL auto_increment,
    READERID int NOT NULL,
    DOCID int NOT NULL,
    COPYNO int NOT NULL,
    LIBID int NOT NULL,
    DTIME DATETIME,
    PRIMARY KEY (RESUMBER),
    FOREIGN KEY (READERID) REFERENCES READER(READERID),
    FOREIGN KEY (DOCID,COPYNO,LIBID) REFERENCES COPY(DOCID,COPYNO,LIBID)
    );    
    

CREATE TABLE BORROWS (
    BORNUMBER int NOT NULL auto_increment,
    READERID int NOT NULL,
    DOCID int NOT NULL,
    COPYNO int NOT NULL,
    LIBID int NOT NULL,
    BDTIME DATETIME,
    RDTIME DATETIME default null,
    PRIMARY KEY (BORNUMBER),
    FOREIGN KEY (READERID) REFERENCES READER(READERID),
    FOREIGN KEY (DOCID,COPYNO,LIBID) REFERENCES COPY(DOCID,COPYNO,LIBID)
    );   
